import { DESTINATIONS } from '../site-data.js';
import { escapeHtml } from '../lib/escape-html.js';
import { routePath, renderCardImage, renderHeroImage, renderSectionHeading, renderWhatsAppLink } from './components.js';

const COPY = Object.freeze({
  id: Object.freeze({
    eyebrow: 'Wisata Dunia', title: 'Dunia yang dapat dijelajahi bersama', description: 'Mulai dari inspirasi yang ramah keluarga, lalu susun ritme, anggaran, dan kebutuhan yang dapat dikonfirmasi bersama.', destinations: 'Destinasi untuk dibayangkan', families: 'Keluarga & grup', couples: 'Perjalanan berdua', solo: 'Jelajah mandiri', note: 'Contoh perjalanan ini adalah konten statis, bukan jadwal atau ketersediaan langsung.', custom: 'Rencanakan perjalanan kustom', planning: 'Pilih cara bepergian sebelum memilih tempat', planningText: 'Tujuan yang sama dapat terasa berbeda ketika kelompok, tempo, dan tingkat kenyamanan berubah.', questions: 'Pertanyaan awal', questionList: ['Siapa yang ikut dan berapa usia peserta?', 'Berapa banyak perpindahan yang nyaman?', 'Apa batas anggaran, musim, dan kebutuhan aksesibilitas?'], explore: 'Buka catatan destinasi'
  }),
  en: Object.freeze({
    eyebrow: 'Worldwide Travel', title: 'A world to explore together', description: 'Start with family-friendly inspiration, then shape a rhythm, budget, and set of needs to confirm together.', destinations: 'Destinations to imagine', families: 'Family & group', couples: 'Couple journeys', solo: 'Independent discovery', note: 'These journey examples are static content, not live schedules or availability.', custom: 'Plan a custom trip', planning: 'Choose how you travel before choosing where', planningText: 'The same destination can feel different when the group, pace, and comfort level change.', questions: 'Early questions', questionList: ['Who is travelling and what are their ages?', 'How many transfers feel comfortable?', 'What are the budget, season, and accessibility boundaries?'], explore: 'Open destination notes'
  })
});

function copy(locale) { return COPY[locale] ?? COPY.id; }
function label(item, locale) { return item.labels?.[locale] ?? item.labels?.id ?? ''; }
function list(items) { return `<ul class="check-list">${items.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul>`; }

export function renderWorldwideOverview({ locale = 'id' } = {}) {
  const text = copy(locale);
  const personas = [
    [text.families, '/assets/generated/family-group-travel.png', locale === 'en' ? 'Build pauses around children, older travellers, and different energy levels.' : 'Susun jeda berdasarkan anak, lansia, dan tingkat energi yang berbeda.'],
    [text.couples, '/assets/generated/traveler-couple.png', locale === 'en' ? 'Leave room for shared interests, privacy, and a pace that feels like yours.' : 'Sisakan ruang untuk minat bersama, privasi, dan tempo yang terasa sesuai.'],
    [text.solo, '/assets/generated/traveler-solo.png', locale === 'en' ? 'Balance independent time with practical support for transfers, documents, and safety.' : 'Seimbangkan waktu mandiri dengan dukungan praktis untuk transportasi, dokumen, dan keamanan.']
  ];
  return `<div class="worldwide-page"><section class="hero hero--worldwide"><div class="container hero__content"><div>${renderSectionHeading({ eyebrow: text.eyebrow, title: text.title, description: text.description, level: 1 })}<div class="hero__actions"><a class="button button--secondary" href="${escapeHtml(routePath(locale, 'destinations'))}">${escapeHtml(text.destinations)}</a><a class="button button--secondary" href="${escapeHtml(routePath(locale, 'custom-trip'))}">${escapeHtml(text.custom)}</a>${renderWhatsAppLink({ locale, journey: text.eyebrow })}</div></div>${renderHeroImage({ asset: '/assets/generated/hero-worldwide-master.png', mobileAsset: '/assets/generated/hero-worldwide-mobile.png', alt: locale === 'en' ? 'An Indonesian family exploring a sunny coastal village' : 'Keluarga Indonesia menjelajahi desa pesisir yang cerah' })}</div></section><section class="content-section container" data-reveal>${renderSectionHeading({ eyebrow: text.planning, title: text.planning, description: text.planningText })}<div class="content-grid content-grid--three">${personas.map(([title, asset, body]) => `<article class="content-card">${renderCardImage(asset, title)}<h2>${escapeHtml(title)}</h2><p>${escapeHtml(body)}</p></article>`).join('')}</div></section><section class="content-section container" data-reveal>${renderSectionHeading({ eyebrow: text.destinations, title: text.destinations, description: text.note })}<div class="content-grid content-grid--three">${DESTINATIONS.map((item) => `<article class="content-card catalog-card">${renderCardImage(item.image, label(item, locale))}<div><h3><a href="${escapeHtml(routePath(locale, 'destination-detail', { slug: item.slug }))}">${escapeHtml(label(item, locale))}</a></h3><p>${escapeHtml(item.description?.[locale] ?? item.description?.id ?? '')}</p><a href="${escapeHtml(routePath(locale, 'destination-detail', { slug: item.slug }))}">${escapeHtml(text.explore)}</a></div></article>`).join('')}</div></section><section class="content-section container home-split" data-reveal><div class="quiet-card"><h2>${escapeHtml(text.questions)}</h2>${list(text.questionList)}</div><div class="quiet-card"><h2>${escapeHtml(text.custom)}</h2><p>${escapeHtml(text.description)}</p>${renderWhatsAppLink({ locale, journey: text.custom })}</div></section><section class="final-cta"><div class="container"><p>${escapeHtml(text.note)}</p>${renderWhatsAppLink({ locale, journey: text.eyebrow })}</div></section></div>`;
}
